// Copyright the fhir-subscriptions-foss authors.
// SPDX-License-Identifier: Apache-2.0

package audit

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"hash/fnv"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// PgStoreOptions configures NewPgStore.
type PgStoreOptions struct {
	// Schema is the Postgres schema that owns the audit_log table. Empty
	// means the connection's default search path.
	Schema string
}

// PgStore is the durable Postgres-backed audit Store.
//
// Writes serialize through a Postgres advisory lock per LLD §8.2 so
// concurrent appenders see a linear chain. The lock key is a 64-bit
// hash of "audit_chain_serial" — a single, well-known constant — taken
// at module init.
type PgStore struct {
	pool   *pgxpool.Pool
	schema string
	lockID int64
}

// NewPgStore builds a PgStore.
func NewPgStore(pool *pgxpool.Pool, opts PgStoreOptions) (*PgStore, error) {
	if pool == nil {
		return nil, errors.New("audit: pool is required")
	}
	h := fnv.New64a()
	_, _ = h.Write([]byte("audit_chain_serial"))
	lockID := int64(h.Sum64()) //nolint:gosec // intentional truncation; pg lock keys are int64
	return &PgStore{pool: pool, schema: opts.Schema, lockID: lockID}, nil
}

// Migrate creates the audit_log table per LLD §8.1.
func (s *PgStore) Migrate(ctx context.Context) error {
	tableRef := s.qualified("audit_log")
	stmt := fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL,
    actor_kind TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    action TEXT NOT NULL,
    target_kind TEXT NOT NULL,
    target_id TEXT NOT NULL,
    outcome TEXT NOT NULL,
    correlation_id UUID NOT NULL,
    payload JSONB,
    prior_hash BYTEA NOT NULL,
    chain_input BYTEA NOT NULL,
    chain_hash BYTEA NOT NULL
)`, tableRef)
	_, err := s.pool.Exec(ctx, stmt)
	return err
}

// AcquireChainLock takes a session-level advisory lock and returns a
// release that frees it. The release also closes the underlying
// connection back to the pool.
func (s *PgStore) AcquireChainLock(ctx context.Context) (func() error, error) {
	conn, err := s.pool.Acquire(ctx)
	if err != nil {
		return nil, fmt.Errorf("audit/pg: acquire conn: %w", err)
	}
	if _, err := conn.Exec(ctx, "SELECT pg_advisory_lock($1)", s.lockID); err != nil {
		conn.Release()
		return nil, fmt.Errorf("audit/pg: advisory lock: %w", err)
	}
	released := false
	return func() error {
		if released {
			return nil
		}
		released = true
		_, err := conn.Exec(ctx, "SELECT pg_advisory_unlock($1)", s.lockID)
		conn.Release()
		return err
	}, nil
}

// LastChainHash returns the most recent row's chain_hash, or nil when
// the table is empty.
func (s *PgStore) LastChainHash(ctx context.Context) ([]byte, error) {
	var h []byte
	err := s.pool.QueryRow(ctx,
		"SELECT chain_hash FROM "+s.qualified("audit_log")+" ORDER BY seq DESC LIMIT 1",
	).Scan(&h)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return h, nil
}

// InsertAuditRow persists a row.
func (s *PgStore) InsertAuditRow(ctx context.Context, row Row) error {
	payload, err := json.Marshal(row.Payload)
	if err != nil {
		return fmt.Errorf("audit/pg: marshal payload: %w", err)
	}
	cid := row.CorrelationID
	if cid == (uuid.UUID{}) {
		cid = uuid.New()
	}
	_, err = s.pool.Exec(ctx, `
INSERT INTO `+s.qualified("audit_log")+` (
    occurred_at, actor_kind, actor_id, action, target_kind, target_id,
    outcome, correlation_id, payload, prior_hash, chain_input, chain_hash
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12)`,
		row.OccurredAt,
		row.ActorKind,
		row.ActorID,
		row.Action,
		row.TargetKind,
		row.TargetID,
		row.Outcome,
		cid,
		payload,
		row.PriorHash,
		row.ChainInput,
		row.ChainHash,
	)
	return err
}

// IterateRows visits rows in seq order.
func (s *PgStore) IterateRows(ctx context.Context, fn func(Row) error) error {
	rows, err := s.pool.Query(ctx, `
SELECT occurred_at, actor_kind, actor_id, action, target_kind, target_id,
       outcome, correlation_id, payload, prior_hash, chain_input, chain_hash
FROM `+s.qualified("audit_log")+` ORDER BY seq ASC`)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var r Row
		var payload []byte
		var cid uuid.UUID
		if err := rows.Scan(
			&r.OccurredAt,
			&r.ActorKind,
			&r.ActorID,
			&r.Action,
			&r.TargetKind,
			&r.TargetID,
			&r.Outcome,
			&cid,
			&payload,
			&r.PriorHash,
			&r.ChainInput,
			&r.ChainHash,
		); err != nil {
			return err
		}
		r.CorrelationID = cid
		if len(payload) > 0 {
			var m map[string]any
			if err := json.Unmarshal(payload, &m); err == nil {
				r.Payload = m
			}
		}
		if err := fn(r); err != nil {
			return err
		}
	}
	return rows.Err()
}

func (s *PgStore) qualified(name string) string {
	if s.schema == "" {
		return quoteSQLIdent(name)
	}
	return quoteSQLIdent(s.schema) + "." + quoteSQLIdent(name)
}

func quoteSQLIdent(s string) string {
	out := []byte{'"'}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '"' {
			out = append(out, '"', '"')
		} else {
			out = append(out, c)
		}
	}
	out = append(out, '"')
	return string(out)
}
