// Copyright the fhir-ehr-subscriptions-service authors.
// SPDX-License-Identifier: Apache-2.0

package audit

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sync"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// PgStoreOptions configures NewPgStore.
type PgStoreOptions struct {
	// Schema is the Postgres schema that owns the audit_log table. Empty
	// means the connection's default search path.
	Schema string
}

// AuditChainAdvisoryLockID is the documented Postgres advisory lock key
// used to serialize chain appends. Reserved exclusively for the audit
// chain; do not reuse this value for any other advisory lock in the
// service.
//
// The value is the FNV-1a 64-bit hash of the string "audit_chain_serial"
// truncated to int64. Captured here as a constant so a future operator
// can audit which advisory_lock owners are competing for which numeric
// key without grep'ing for the literal string everywhere (N-1).
//
// If you ever need to change this, also rev a migration that releases
// any stranded session-level locks under the old id.
const AuditChainAdvisoryLockID int64 = -1971033306967946433

// PgStore is the durable Postgres-backed audit Store.
//
// Writes serialize through a Postgres advisory lock per LLD §8.2 so
// concurrent appenders see a linear chain. The lock key is the
// documented [AuditChainAdvisoryLockID] constant.
//
// The lock is held with pg_advisory_xact_lock so it is automatically
// released on commit, rollback, OR connection loss; this avoids the
// pre-B-34 hazard where a session-level pg_advisory_lock could leak if
// the writer panicked between INSERT and the manual unlock (LLD §8.2,
// audit B-34).
type PgStore struct {
	pool   *pgxpool.Pool
	schema string
	lockID int64

	// activeTx threads the transaction that AcquireChainLock opened
	// through to InsertAuditRow / LastChainHash on the same goroutine.
	// The store interface is contracted to be called single-threaded
	// per Acquire/Insert/release cycle (Writer.Emit serializes through
	// the chain lock); we still guard with a mutex so a stray
	// concurrent caller fails loudly rather than corrupts the chain.
	txMu     sync.Mutex
	activeTx pgx.Tx
}

// NewPgStore builds a PgStore.
func NewPgStore(pool *pgxpool.Pool, opts PgStoreOptions) (*PgStore, error) {
	if pool == nil {
		return nil, errors.New("audit: pool is required")
	}
	return &PgStore{pool: pool, schema: opts.Schema, lockID: AuditChainAdvisoryLockID}, nil
}

// Migrate creates the audit_log table per LLD §8.1.
func (s *PgStore) Migrate(ctx context.Context) error {
	tableRef := s.qualified("audit_log")
	stmt := fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL,
    actor_kind TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    action TEXT NOT NULL,
    target_kind TEXT NOT NULL,
    target_id TEXT NOT NULL,
    outcome TEXT NOT NULL,
    correlation_id UUID NOT NULL,
    payload JSONB,
    prior_hash BYTEA NOT NULL,
    chain_input BYTEA NOT NULL,
    chain_hash BYTEA NOT NULL
)`, tableRef)
	_, err := s.pool.Exec(ctx, stmt)
	return err
}

// AcquireChainLock begins a transaction and takes a transaction-scoped
// advisory lock (pg_advisory_xact_lock). The returned release commits
// the transaction, which auto-releases the lock.
//
// Transaction-scoped (rather than session-scoped) means a panic, a
// rollback, OR a lost connection all release the lock without manual
// intervention — this is the B-34 fix: the prior session-level
// pg_advisory_lock could leak forever if the writer panicked between
// INSERT and the manual unlock.
func (s *PgStore) AcquireChainLock(ctx context.Context) (func() error, error) {
	s.txMu.Lock()
	if s.activeTx != nil {
		s.txMu.Unlock()
		return nil, errors.New("audit/pg: chain lock already held; concurrent Acquire is a contract violation")
	}
	tx, err := s.pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		s.txMu.Unlock()
		return nil, fmt.Errorf("audit/pg: begin tx: %w", err)
	}
	if _, err := tx.Exec(ctx, "SELECT pg_advisory_xact_lock($1)", s.lockID); err != nil {
		_ = tx.Rollback(ctx)
		s.txMu.Unlock()
		return nil, fmt.Errorf("audit/pg: advisory xact lock: %w", err)
	}
	s.activeTx = tx
	s.txMu.Unlock()

	released := false
	return func() error {
		s.txMu.Lock()
		defer s.txMu.Unlock()
		if released {
			return nil
		}
		released = true
		active := s.activeTx
		s.activeTx = nil
		if active == nil {
			return nil
		}
		// Commit releases the xact-scoped advisory lock. If commit
		// fails, fall back to rollback — both flavors release the
		// lock.
		if err := active.Commit(ctx); err != nil {
			_ = active.Rollback(ctx)
			return fmt.Errorf("audit/pg: commit chain tx: %w", err)
		}
		return nil
	}, nil
}

// LastChainHash returns the most recent row's chain_hash, or nil when
// the table is empty. When the chain transaction is active (between
// AcquireChainLock and the matching release) the read runs inside that
// transaction so the lock + read + insert sequence is atomic.
func (s *PgStore) LastChainHash(ctx context.Context) ([]byte, error) {
	tx := s.currentTx()
	var h []byte
	stmt := "SELECT chain_hash FROM " + s.qualified("audit_log") + " ORDER BY seq DESC LIMIT 1"
	var row pgx.Row
	if tx != nil {
		row = tx.QueryRow(ctx, stmt)
	} else {
		row = s.pool.QueryRow(ctx, stmt)
	}
	err := row.Scan(&h)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return h, nil
}

func (s *PgStore) currentTx() pgx.Tx {
	s.txMu.Lock()
	defer s.txMu.Unlock()
	return s.activeTx
}

// InsertAuditRow persists a row. When the chain transaction is active
// (between AcquireChainLock and release) the insert runs inside that
// transaction; otherwise it runs against the pool directly.
func (s *PgStore) InsertAuditRow(ctx context.Context, row Row) error {
	payload, err := json.Marshal(row.Payload)
	if err != nil {
		return fmt.Errorf("audit/pg: marshal payload: %w", err)
	}
	cid := row.CorrelationID
	if cid == (uuid.UUID{}) {
		cid = uuid.New()
	}
	stmt := `
INSERT INTO ` + s.qualified("audit_log") + ` (
    occurred_at, actor_kind, actor_id, action, target_kind, target_id,
    outcome, correlation_id, payload, prior_hash, chain_input, chain_hash
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12)`
	args := []any{
		row.OccurredAt,
		row.ActorKind,
		row.ActorID,
		row.Action,
		row.TargetKind,
		row.TargetID,
		row.Outcome,
		cid,
		payload,
		row.PriorHash,
		row.ChainInput,
		row.ChainHash,
	}
	tx := s.currentTx()
	if tx != nil {
		_, err = tx.Exec(ctx, stmt, args...)
	} else {
		_, err = s.pool.Exec(ctx, stmt, args...)
	}
	return err
}

// IterateRows visits rows in seq order.
func (s *PgStore) IterateRows(ctx context.Context, fn func(Row) error) error {
	rows, err := s.pool.Query(ctx, `
SELECT occurred_at, actor_kind, actor_id, action, target_kind, target_id,
       outcome, correlation_id, payload, prior_hash, chain_input, chain_hash
FROM `+s.qualified("audit_log")+` ORDER BY seq ASC`)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var r Row
		var payload []byte
		var cid uuid.UUID
		if err := rows.Scan(
			&r.OccurredAt,
			&r.ActorKind,
			&r.ActorID,
			&r.Action,
			&r.TargetKind,
			&r.TargetID,
			&r.Outcome,
			&cid,
			&payload,
			&r.PriorHash,
			&r.ChainInput,
			&r.ChainHash,
		); err != nil {
			return err
		}
		r.CorrelationID = cid
		if len(payload) > 0 {
			var m map[string]any
			if err := json.Unmarshal(payload, &m); err == nil {
				r.Payload = m
			}
		}
		if err := fn(r); err != nil {
			return err
		}
	}
	return rows.Err()
}

func (s *PgStore) qualified(name string) string {
	if s.schema == "" {
		return quoteSQLIdent(name)
	}
	return quoteSQLIdent(s.schema) + "." + quoteSQLIdent(name)
}

func quoteSQLIdent(s string) string {
	out := []byte{'"'}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '"' {
			out = append(out, '"', '"')
		} else {
			out = append(out, c)
		}
	}
	out = append(out, '"')
	return string(out)
}
