package com.bzonfhir.subscriptionservice.spi.meta

import java.time.Instant

/**
 * The canonical in-flight message shape that flows between SPI surfaces.
 *
 * Every [com.bzonfhir.subscriptionservice.spi.IngestSource] produces
 * [PipelineMessage]s; downstream stages (mapping, persistence, sinks)
 * accept them. The shape is INTENTIONALLY narrow — we want the SPI to
 * cover HL7 v2 messages, FHIR polling payloads, native REST blobs, and
 * eventually flat-file CSVs without forcing every ingest to invent its
 * own envelope.
 *
 * The split between [raw], [contentType], and [attributes] mirrors how
 * the receive path already works (see `IngestRoutes.kt`):
 *
 *   - `raw` is the bytes as they came off the wire, unmodified, so we
 *     can persist or replay them faithfully.
 *   - `contentType` tells the next stage which parser/mapper family to
 *     pick (`application/hl7-v2`, `application/fhir+json`, etc.).
 *   - `attributes` carries everything ELSE the ingest knows about the
 *     message — for HL7 v2 that's MSH-3 / MSH-9 / MSH-10; for an Athena
 *     poll that's practice id + endpoint + last-modified timestamp.
 *     Keyed by string so additional metadata doesn't break the SPI
 *     when an ingest gains a new attribute.
 *
 * Correlation: every message carries a [correlationId] from the moment
 * the ingest creates it. This is the same id that propagates through
 * MDC, OTel attributes, persisted rows, and outbound HTTP headers. See
 * `interface-engine/.../observability/CorrelationId.kt` for the generator
 * and `IngestRoutes.kt` for how it's pinned at receive time today.
 *
 * @property correlationId UUID v4 string. Generated by the ingest if the
 *   inbound protocol has no native correlation header; for protocols
 *   that do (e.g. inbound HTTP with `X-Correlation-Id`), the ingest
 *   should accept the inbound value verbatim.
 * @property receivedAt When the ingest first saw the message. Used by the
 *   observability layer for end-to-end latency calculations.
 * @property sourceProtocol Free-text identifier of the ingest protocol
 *   (matches `IngestSource.protocol`). Stored on the persisted row so
 *   downstream readers can pick the right re-parse strategy.
 * @property sourceSystem A protocol-specific "who sent this" identifier.
 *   For HL7 v2 this is MSH-3 (sending application). For Athena native
 *   REST this is the practice id. For a generic FHIR polling source
 *   this is the base URL of the server we polled. Used in conjunction
 *   with [sourceId] as the (system, id) idempotency key.
 * @property sourceId A protocol-specific message identifier. For HL7 v2
 *   this is MSH-10 (message control id). For a polled FHIR resource
 *   this is the resource's logical id. The (sourceSystem, sourceId)
 *   pair must be unique within a tenant.
 * @property raw The unmodified message bytes as they arrived. May be
 *   plain ASCII (HL7 v2 ER7), UTF-8 JSON, base64-encoded binary, or
 *   any other on-wire shape. The pipeline does not interpret these
 *   bytes until a mapper picks them up.
 * @property contentType IANA media type or our own well-known string
 *   (`application/hl7-v2`, `application/fhir+json`, `application/json`).
 *   Determines which mapping / quirk pipeline runs next.
 * @property attributes Open-ended per-message metadata the ingest wants
 *   to attach. Map keys are namespaced by convention
 *   (`"hl7.controlId"`, `"hl7.messageType"`, `"athena.practiceId"`).
 *   Values are strings so the map serializes cleanly to JSON for
 *   inspection in the operator UI.
 */
data class PipelineMessage(
    val correlationId: String,
    val receivedAt: Instant,
    val sourceProtocol: String,
    val sourceSystem: String,
    val sourceId: String,
    val raw: ByteArray,
    val contentType: String,
    val attributes: Map<String, String> = emptyMap(),
) {
    // ByteArray needs custom equals/hashCode because the default data-class
    // implementations use identity comparison on array fields, which would
    // make two PipelineMessage instances with the same bytes test as not
    // equal. We compare bytes structurally — the only sensible answer for
    // a wire-payload class.
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is PipelineMessage) return false
        return correlationId == other.correlationId &&
            receivedAt == other.receivedAt &&
            sourceProtocol == other.sourceProtocol &&
            sourceSystem == other.sourceSystem &&
            sourceId == other.sourceId &&
            raw.contentEquals(other.raw) &&
            contentType == other.contentType &&
            attributes == other.attributes
    }

    override fun hashCode(): Int {
        var result = correlationId.hashCode()
        result = 31 * result + receivedAt.hashCode()
        result = 31 * result + sourceProtocol.hashCode()
        result = 31 * result + sourceSystem.hashCode()
        result = 31 * result + sourceId.hashCode()
        result = 31 * result + raw.contentHashCode()
        result = 31 * result + contentType.hashCode()
        result = 31 * result + attributes.hashCode()
        return result
    }
}
