// Copyright the fhir-ehr-subscriptions-service authors.
// SPDX-License-Identifier: Apache-2.0

//go:build e2e_realstack

// Package load is the H3 LoadDriver — a thin Go wrapper around the
// real `vegeta` CLI binary that drives sustained N RPS at the
// realstack-running production binary's HTTP listeners and asserts
// real response codes (including 429) and real Retry-After headers.
//
// This package implements docs/e2e-coverage-strategy.md §3.H3 and
// OpenProject story #258. It is consumed by rate-limit and admission
// control e2e tests that need to drive the binary into saturation
// and observe the real wire-path behavior of
// internal/api/auth/handler_rate_limit.go and the token-endpoint
// rate limiter.
//
// # No in-process load substitute
//
// The package contains no in-process load generator. The H3 contract
// requires that all load is generated by a real `vegeta` subprocess
// invoked via os/exec; importing `github.com/tsenart/vegeta/lib`
// would silently substitute an in-process implementation when the CLI
// is missing, so this package never imports it. If the `vegeta` CLI
// is not on PATH, callers should skip the test (see Run, which
// returns a clear "vegeta not found" error rather than degrading to
// an in-process generator).
//
// # Build tag
//
// Files in this package are gated behind the `e2e_realstack` build
// tag so `go build ./...` and `go test ./...` skip the harness by
// default. CI runs the LoadDriver suite with:
//
//	go test -tags e2e_realstack -count=1 ./e2e/realstack/load/...
//
// # Real wall clock
//
// All durations are real — Spec.Duration is passed verbatim to
// vegeta's -duration flag, and Result.Subprocess.Elapsed is measured
// against time.Now (no fake clock indirection). The story acceptance
// criterion that "tests use real wall clock against the real binary"
// is enforced by the absence of any clock interface in the public
// API.
package load
