// Copyright the fhir-ehr-subscriptions-service authors.
// SPDX-License-Identifier: Apache-2.0

//go:build e2e_realstack

// Phase A (RED) tests for OpenProject story #258 — H3 LoadDriver.
//
// These tests pin the public contract of the e2e/realstack/load/ package.
// They fail today because the package's API (`Run`, `Result`,
// `ScenarioSubscriptionCreate429`, `ScenarioWSBindingToken429`) does
// not yet exist. Phase B implements the package as a thin wrapper
// around the real `vegeta` CLI; Phase C audits that the load is
// generated by the real subprocess (no in-process / `vegeta/lib`
// substitute) and that real wall clock + real Keycloak tokens are
// used.
//
// Build tag `e2e_realstack` keeps these out of `make test` and
// `make e2e` (the latter uses the `e2e` tag). Run them with:
//
//	go test -tags e2e_realstack -count=1 ./e2e/realstack/load/...
//
// The tag isolates the harness suite from the unit + legacy e2e
// suites because each Boot call docker-compose-up's the full stack
// (~10 containers) and is too heavy for the default test target.
//
// Acceptance criteria mapped to test names:
//
//   - real vegeta subprocess on PATH                   -> TestLoad_UsesRealVegetaSubprocess
//   - sustained 300 RPS for 30s -> >=45 status 429     -> TestLoad_SubscriptionCreate_Burst429RatioMet
//   - 429 responses carry real Retry-After (positive)  -> TestLoad_SubscriptionCreate_RetryAfterIsPositiveInteger
//   - tokens minted by real Keycloak                   -> TestLoad_TokensMintedByRealKeycloak
//   - real wall clock (no simulated time)              -> TestLoad_UsesRealWallClock
//   - no in-process load substitute                    -> TestLoad_NoInProcessLoadSubstitute
//   - WS binding token rate limit fires under load     -> TestLoad_WSBindingToken_Burst429RatioMet
package load_test

import (
	"context"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/bzimbelman/fhir-ehr-subscriptions-service/e2e/realstack"
	"github.com/bzimbelman/fhir-ehr-subscriptions-service/e2e/realstack/load"
)

// bootTimeout is the wall-clock budget for booting the real-stack
// before each load test. Matches the H1 harness budget plus a small
// margin for the load run itself.
const bootTimeout = 3 * time.Minute

// requireDocker skips the test if docker / docker compose isn't
// usable on the host. Mirrors the H1 harness's gate.
func requireDocker(t *testing.T) {
	t.Helper()
	if err := realstack.CheckDocker(); err != nil {
		t.Skipf("docker unavailable: %v", err)
	}
}

// requireVegeta skips the test if the real `vegeta` CLI is not on
// PATH. The story explicitly forbids substituting an in-process load
// generator, so a missing CLI must produce a skip — never a mocked
// pass.
func requireVegeta(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("vegeta"); err != nil {
		t.Skipf("vegeta CLI not on PATH (install from https://github.com/tsenart/vegeta): %v", err)
	}
}

// bootStackWithLowRateLimits boots the realstack with auth rate
// limits configured low enough that a 300 RPS burst sustained for 30s
// drives the limiter into 429 territory. Returns the booted stack and
// a real-Keycloak-minted bearer token usable against the binary.
func bootStackWithLowRateLimits(t *testing.T) (*realstack.Stack, string) {
	t.Helper()
	requireDocker(t)

	ctx, cancel := context.WithTimeout(context.Background(), bootTimeout)
	defer cancel()

	stack := realstack.Boot(ctx, t, realstack.Options{
		// Configure the rate limiters tight: 5 burst with a 1
		// req/s refill, so 300 RPS for 30s produces ~9000
		// requests; only ~5+30 should pass, the rest must 429.
		SubscriptionCreateRateLimit: realstack.RateLimit{
			Burst:           5,
			RefillPerSecond: 1,
			MaxKeys:         1024,
		},
		WSBindingTokenRateLimit: realstack.RateLimit{
			Burst:           5,
			RefillPerSecond: 1,
			MaxKeys:         1024,
		},
	})
	t.Cleanup(stack.Close)

	tok, err := stack.MintClientToken(ctx)
	if err != nil {
		t.Fatalf("mint client token via real Keycloak: %v", err)
	}
	if tok == "" {
		t.Fatalf("real Keycloak returned empty access token")
	}
	return stack, tok
}

// TestLoad_UsesRealVegetaSubprocess proves the load driver shells out
// to the real `vegeta` binary on PATH. The test asserts that the
// subprocess pid recorded in the Result is a live OS process that was
// spawned with argv[0] == "vegeta" (or the absolute path resolved to
// the same basename).
func TestLoad_UsesRealVegetaSubprocess(t *testing.T) {
	requireVegeta(t)
	stack, token := bootStackWithLowRateLimits(t)

	res := load.Run(t, load.Spec{
		Name:      "smoke",
		TargetURL: stack.Binary.URL + "/readyz",
		Method:    http.MethodGet,
		Token:     token,
		Rate:      10,
		Duration:  500 * time.Millisecond,
	})

	if res.Subprocess.Path == "" {
		t.Fatalf("Result.Subprocess.Path is empty; load driver did not record a real vegeta exec")
	}
	if filepath.Base(res.Subprocess.Path) != "vegeta" {
		t.Fatalf("Result.Subprocess.Path basename = %q, want %q", filepath.Base(res.Subprocess.Path), "vegeta")
	}
	if res.Subprocess.PID <= 0 {
		t.Fatalf("Result.Subprocess.PID = %d, want a real OS PID > 0", res.Subprocess.PID)
	}
	// The process must have actually exited cleanly (exit code 0
	// is fine; vegeta returns non-zero on its own errors).
	if !res.Subprocess.Exited {
		t.Fatalf("vegeta subprocess never exited; the run did not complete")
	}
}

// TestLoad_SubscriptionCreate_Burst429RatioMet drives 300 RPS at
// POST /Subscription for 30s through the real binary's auth +
// rate-limit middleware and asserts that >=45 responses carry status
// 429 — the example shape stated in the story acceptance criteria.
//
// The threshold is conservative: with Burst=5 + Refill=1 r/s, the
// expected 429 count over 30s × 300 RPS is ~9000 - 35 = ~8965; the
// >=45 floor leaves 200x headroom for minor scheduling noise yet still
// guarantees the limiter is on the wire path.
func TestLoad_SubscriptionCreate_Burst429RatioMet(t *testing.T) {
	requireVegeta(t)
	stack, token := bootStackWithLowRateLimits(t)

	res := load.Run(t, load.Spec{
		Name:      "subscription-create-burst",
		TargetURL: stack.Binary.URL + "/Subscription",
		Method:    http.MethodPost,
		Body:      []byte(minimalSubscriptionJSON),
		Headers: http.Header{
			"Content-Type": []string{"application/fhir+json"},
		},
		Token:    token,
		Rate:     300,
		Duration: 30 * time.Second,
	})

	got429 := res.StatusCounts[http.StatusTooManyRequests]
	if got429 < 45 {
		t.Fatalf("status 429 count = %d, want >=45 (acceptance: 300 RPS × 30s with Burst=5/Refill=1 must produce >=45 real 429s); statusCounts=%v",
			got429, res.StatusCounts)
	}
	// Sanity: the run actually produced enough samples to make
	// the 429 ratio meaningful. 300 RPS × 30s is 9000 expected;
	// be lenient on jitter but reject runs that didn't actually
	// drive load.
	if res.TotalRequests < 5000 {
		t.Fatalf("vegeta only sent %d requests at 300 RPS for 30s; load driver did not actually drive load", res.TotalRequests)
	}
}

// TestLoad_SubscriptionCreate_RetryAfterIsPositiveInteger asserts the
// 429 responses returned under sustained load carry a real,
// positive-integer Retry-After header — matching the production
// auth.handler_rate_limit middleware contract pinned in
// internal/api/auth/handler_rate_limit_test.go::
// TestClientRateLimiter_RetryAfterIsPositiveInteger.
func TestLoad_SubscriptionCreate_RetryAfterIsPositiveInteger(t *testing.T) {
	requireVegeta(t)
	stack, token := bootStackWithLowRateLimits(t)

	res := load.Run(t, load.Spec{
		Name:      "subscription-create-retry-after",
		TargetURL: stack.Binary.URL + "/Subscription",
		Method:    http.MethodPost,
		Body:      []byte(minimalSubscriptionJSON),
		Headers: http.Header{
			"Content-Type": []string{"application/fhir+json"},
		},
		Token:    token,
		Rate:     300,
		Duration: 5 * time.Second,
		// Capture per-response headers so the test can audit
		// Retry-After. Vegeta must be invoked with -output and
		// the report parser must surface response headers.
		CaptureResponseHeaders: true,
	})

	if len(res.RetryAfterValues) == 0 {
		t.Fatalf("no Retry-After header values captured from any 429 response; rate-limit middleware contract broken or load driver dropped headers")
	}
	for i, v := range res.RetryAfterValues {
		secs, err := strconv.Atoi(v)
		if err != nil {
			t.Fatalf("Retry-After[%d]=%q is not an integer-seconds value: %v", i, v, err)
		}
		if secs <= 0 {
			t.Fatalf("Retry-After[%d]=%d, want positive integer seconds", i, secs)
		}
	}
}

// TestLoad_TokensMintedByRealKeycloak asserts the bearer token used
// in the load run was minted by the real Keycloak container, not a
// pre-baked dev-bypass token. The check: parse the JWT from the
// Authorization header the load driver sent, decode the issuer claim,
// confirm it matches stack.Keycloak.IssuerURL.
func TestLoad_TokensMintedByRealKeycloak(t *testing.T) {
	requireVegeta(t)
	stack, token := bootStackWithLowRateLimits(t)

	iss, err := jwtIssuerClaim(token)
	if err != nil {
		t.Fatalf("decode JWT issuer claim from minted token: %v", err)
	}
	want := stack.Keycloak.IssuerURL
	if iss != want {
		t.Fatalf("token issuer = %q, want real Keycloak issuer %q (was the token a pre-baked dev fake?)", iss, want)
	}

	// Drive a tiny load run so the test fails if Run drops the
	// Authorization header or rewrites the token.
	res := load.Run(t, load.Spec{
		Name:      "token-on-wire",
		TargetURL: stack.Binary.URL + "/Subscription",
		Method:    http.MethodPost,
		Body:      []byte(minimalSubscriptionJSON),
		Headers: http.Header{
			"Content-Type": []string{"application/fhir+json"},
		},
		Token:    token,
		Rate:     5,
		Duration: 500 * time.Millisecond,
	})

	if res.AuthorizationHeaderSeen != "Bearer "+token {
		t.Fatalf("load driver sent Authorization=%q, want Bearer <minted-token>; the real Keycloak token must reach the binary",
			res.AuthorizationHeaderSeen)
	}
}

// TestLoad_UsesRealWallClock asserts the load run measures real
// elapsed time. Spec.Duration must be respected against the OS clock,
// not a faked one. Floor: a Duration=2s run must take >=1.8s and
// <=4s wall-clock (allowing for vegeta startup/teardown).
func TestLoad_UsesRealWallClock(t *testing.T) {
	requireVegeta(t)
	stack, token := bootStackWithLowRateLimits(t)

	start := time.Now()
	_ = load.Run(t, load.Spec{
		Name:      "wall-clock",
		TargetURL: stack.Binary.URL + "/readyz",
		Method:    http.MethodGet,
		Token:     token,
		Rate:      50,
		Duration:  2 * time.Second,
	})
	elapsed := time.Since(start)

	if elapsed < 1800*time.Millisecond {
		t.Fatalf("Run for 2s elapsed in %v; load driver appears to use simulated time", elapsed)
	}
	if elapsed > 6*time.Second {
		t.Fatalf("Run for 2s elapsed in %v; load driver took an absurd amount of time", elapsed)
	}
}

// TestLoad_NoInProcessLoadSubstitute audits the package source to
// guarantee the H3 contract: the load driver must not import
// `github.com/tsenart/vegeta/lib` (or any other in-process load
// generator) as a substitute for the real subprocess. The Go-language
// import is also forbidden because it would silently degrade the
// driver to in-process load if the CLI is missing — the no-fakes
// rule for epic #91 forbids any such fallback.
func TestLoad_NoInProcessLoadSubstitute(t *testing.T) {
	pkgDir := loadPackageDir(t)

	forbidden := []string{
		`"github.com/tsenart/vegeta/lib"`,
		`"github.com/tsenart/vegeta/v12/lib"`,
		`vegeta.NewAttacker`,
		`vegeta.Attack`,
	}

	entries, err := os.ReadDir(pkgDir)
	if err != nil {
		t.Fatalf("read package dir: %v", err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		// Skip _test.go files: this very file mentions the
		// strings literally as forbidden tokens.
		if strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(pkgDir, e.Name())
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		body := string(raw)
		for _, needle := range forbidden {
			if strings.Contains(body, needle) {
				t.Errorf("%s contains forbidden in-process load substitute %q; the H3 contract requires the real `vegeta` CLI subprocess",
					path, needle)
			}
		}
	}
}

// TestLoad_WSBindingToken_Burst429RatioMet drives sustained load at
// the $get-ws-binding-token operation and asserts the
// WSBindingTokenRateLimit middleware fires under saturation,
// matching Spec.Auth.WSBindingTokenRateLimit configured by Boot.
func TestLoad_WSBindingToken_Burst429RatioMet(t *testing.T) {
	requireVegeta(t)
	stack, token := bootStackWithLowRateLimits(t)

	target, err := url.Parse(stack.Binary.URL + "/Subscription/sub-1/$get-ws-binding-token")
	if err != nil {
		t.Fatalf("parse target URL: %v", err)
	}

	res := load.Run(t, load.Spec{
		Name:      "ws-binding-token-burst",
		TargetURL: target.String(),
		Method:    http.MethodPost,
		Token:     token,
		Headers: http.Header{
			"Content-Type": []string{"application/fhir+json"},
		},
		Body:     []byte(`{"resourceType":"Parameters"}`),
		Rate:     300,
		Duration: 30 * time.Second,
	})

	got429 := res.StatusCounts[http.StatusTooManyRequests]
	if got429 < 45 {
		t.Fatalf("status 429 count for $get-ws-binding-token = %d, want >=45; statusCounts=%v",
			got429, res.StatusCounts)
	}
}

// loadPackageDir walks up from the cwd to find the e2e/realstack/load
// package directory. Used by TestLoad_NoInProcessLoadSubstitute to
// audit non-test source files.
func loadPackageDir(t *testing.T) string {
	t.Helper()
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	// Walk up until we find a "go.mod"; the load package lives at
	// <repo-root>/e2e/realstack/load.
	dir := cwd
	for i := 0; i < 8; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return filepath.Join(dir, "e2e", "realstack", "load")
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatalf("could not find repo root from cwd %q", cwd)
	return ""
}

// minimalSubscriptionJSON is a smallest-possible R5 Subscription
// resource the binary will accept for parse-and-rate-limit purposes.
// The rate limiter sits in front of body validation, so even an
// invalid Subscription suffices to drive 429.
const minimalSubscriptionJSON = `{
  "resourceType": "Subscription",
  "status": "requested",
  "topic": "http://example.org/topics/encounter-create",
  "channelType": {"system": "http://terminology.hl7.org/CodeSystem/subscription-channel-type", "code": "rest-hook"},
  "endpoint": "http://example.com/cb"
}`
