// Copyright the fhir-ehr-subscriptions-service authors.
// SPDX-License-Identifier: Apache-2.0

//go:build e2e_realstack

package load

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Spec describes a single load run.
//
// All fields except Name and TargetURL have sane zero-value
// behavior; Method defaults to GET, Rate defaults to 10 RPS,
// Duration defaults to 1s. The H3 contract assumes the caller
// already booted a realstack via realstack.Boot and minted a real
// Keycloak token via Stack.MintClientToken.
type Spec struct {
	// Name is a human-readable label included in error messages
	// and in the on-disk artifact filenames so concurrent runs
	// don't collide. Required.
	Name string

	// TargetURL is the absolute URL the load will be aimed at.
	// Typically `<stack.Binary.URL>/Subscription` or similar.
	// Required.
	TargetURL string

	// Method is the HTTP method. Defaults to GET.
	Method string

	// Body, when non-nil, is sent as the request body on every
	// request in the run. Vegeta materializes the bytes once and
	// reuses them, which matches a real client retrying the same
	// payload under load.
	Body []byte

	// Headers are extra request headers sent on every request.
	// Authorization is set from Token (do not duplicate it here).
	Headers http.Header

	// Token is the real Keycloak-minted bearer token sent in the
	// Authorization header. Empty disables the header (used by
	// the smoke test against /readyz).
	Token string

	// Rate is the target requests-per-second. Zero defaults to
	// 10. Vegeta turns this into a uniform attacker (no jitter).
	Rate int

	// Duration is the wall-clock duration of the run. Zero
	// defaults to 1s.
	Duration time.Duration

	// CaptureResponseHeaders, when true, parses every response's
	// headers (via `vegeta encode -to=json`) so Result.RetryAfterValues
	// can be populated. The default-off shape keeps low-load smoke
	// runs cheap.
	CaptureResponseHeaders bool
}

// Result is what Run produces.
type Result struct {
	// TotalRequests is the number of responses vegeta recorded.
	TotalRequests int

	// StatusCounts maps HTTP status code -> count of responses.
	// Includes the synthetic code 0 for transport errors.
	StatusCounts map[int]int

	// RetryAfterValues holds the raw Retry-After header strings
	// from every 429 response (only populated when Spec.CaptureResponseHeaders
	// is true). Order matches the response stream.
	RetryAfterValues []string

	// AuthorizationHeaderSeen captures the Authorization request
	// header the load driver actually sent (read back from the
	// vegeta targets file just before invocation). Used by tests
	// that need to prove the real Keycloak token reached the
	// binary.
	AuthorizationHeaderSeen string

	// Subprocess captures details about the real vegeta exec.
	Subprocess SubprocessInfo
}

// SubprocessInfo records details about the real vegeta CLI invocation
// the load run drove. Tests use these fields to audit that the load
// was generated by a real OS process and not an in-process substitute.
type SubprocessInfo struct {
	// Path is the absolute path resolved by exec.LookPath at the
	// time of the run.
	Path string
	// PID is the OS PID of the vegeta child process.
	PID int
	// Exited is true once the process exited (cleanly or otherwise).
	Exited bool
	// ExitCode is the OS exit code from the vegeta child. 0 on a
	// clean run.
	ExitCode int
	// Elapsed is the wall-clock time the run took, measured against
	// time.Now around the exec.Cmd.Run call.
	Elapsed time.Duration
}

// Run executes a single load run against TargetURL using the real
// `vegeta` CLI. Failures (missing binary, bad spec, vegeta non-zero
// exit, malformed JSON output) abort the test via t.Fatalf.
//
// The function shells out twice:
//
//  1. `vegeta attack -duration=... -rate=... -targets=... -output=results.bin`
//  2. `vegeta encode -to=json results.bin` (only when the test needs
//     per-response data; for plain status-counts a `vegeta report
//     -type=json` invocation is enough).
//
// All artifacts (targets file, body file, results.bin, results.json)
// live under t.TempDir so they get cleaned up automatically.
func Run(t *testing.T, spec Spec) Result {
	t.Helper()

	if spec.Name == "" {
		t.Fatalf("load.Run: Spec.Name is required")
	}
	if spec.TargetURL == "" {
		t.Fatalf("load.Run: Spec.TargetURL is required")
	}
	if spec.Method == "" {
		spec.Method = http.MethodGet
	}
	if spec.Rate <= 0 {
		spec.Rate = 10
	}
	if spec.Duration <= 0 {
		spec.Duration = time.Second
	}

	vegetaPath, err := exec.LookPath("vegeta")
	if err != nil {
		t.Fatalf("load.Run: vegeta CLI not on PATH (install from https://github.com/tsenart/vegeta): %v", err)
	}

	dir := t.TempDir()

	// Materialize the body to a file so vegeta's `@<path>` directive
	// can stream it. Vegeta opens the file once per attack, not once
	// per request.
	var bodyPath string
	if len(spec.Body) > 0 {
		bodyPath = filepath.Join(dir, spec.Name+".body")
		if werr := os.WriteFile(bodyPath, spec.Body, 0o600); werr != nil {
			t.Fatalf("load.Run: write body file: %v", werr)
		}
	}

	// Render the vegeta targets file. The format is:
	//   <METHOD> <URL>
	//   <Header-Name>: <value>
	//   ...
	//   @<body-file>     (optional)
	//   <blank line separates targets; we only have one target)
	var targets bytes.Buffer
	fmt.Fprintf(&targets, "%s %s\n", spec.Method, spec.TargetURL)
	headers := http.Header{}
	for k, vs := range spec.Headers {
		for _, v := range vs {
			headers.Add(k, v)
		}
	}
	authzSeen := ""
	if spec.Token != "" {
		authzSeen = "Bearer " + spec.Token
		headers.Set("Authorization", authzSeen)
	}
	for k, vs := range headers {
		for _, v := range vs {
			fmt.Fprintf(&targets, "%s: %s\n", k, v)
		}
	}
	if bodyPath != "" {
		fmt.Fprintf(&targets, "@%s\n", bodyPath)
	}

	targetsPath := filepath.Join(dir, spec.Name+".targets")
	if werr := os.WriteFile(targetsPath, targets.Bytes(), 0o600); werr != nil {
		t.Fatalf("load.Run: write targets file: %v", werr)
	}

	resultsPath := filepath.Join(dir, spec.Name+".bin")

	attackArgs := []string{
		"attack",
		"-duration=" + spec.Duration.String(),
		"-rate=" + fmt.Sprintf("%d/1s", spec.Rate),
		"-targets=" + targetsPath,
		"-output=" + resultsPath,
		"-keepalive=true",
		// Set a reasonable timeout slightly above the run
		// duration so individual slow responses don't kill the
		// run; vegeta default is 30s which is too long for our
		// short tests.
		"-timeout=" + (spec.Duration + 5*time.Second).String(),
	}

	attackCmd := exec.Command(vegetaPath, attackArgs...)
	attackCmd.Stderr = os.Stderr // surface vegeta diagnostics to test logs

	start := time.Now()
	if serr := attackCmd.Start(); serr != nil {
		t.Fatalf("load.Run: start vegeta attack: %v", serr)
	}
	pid := attackCmd.Process.Pid

	waitErr := attackCmd.Wait()
	elapsed := time.Since(start)

	res := Result{
		StatusCounts:            map[int]int{},
		AuthorizationHeaderSeen: authzSeen,
		Subprocess: SubprocessInfo{
			Path:     vegetaPath,
			PID:      pid,
			Exited:   true,
			ExitCode: attackCmd.ProcessState.ExitCode(),
			Elapsed:  elapsed,
		},
	}

	if waitErr != nil {
		// vegeta returns non-zero on its own errors (e.g.
		// invalid targets); surface to test.
		t.Fatalf("load.Run: vegeta attack failed (exit=%d): %v", res.Subprocess.ExitCode, waitErr)
	}

	// Always run `vegeta report -type=json` to get totals + status
	// histogram. Cheap.
	reportCmd := exec.Command(vegetaPath, "report", "-type=json", resultsPath)
	reportOut, err := reportCmd.Output()
	if err != nil {
		t.Fatalf("load.Run: vegeta report: %v\n%s", err, reportOut)
	}
	var report struct {
		Requests    int            `json:"requests"`
		StatusCodes map[string]int `json:"status_codes"`
	}
	if err := json.Unmarshal(reportOut, &report); err != nil {
		t.Fatalf("load.Run: parse vegeta report JSON: %v\nraw=%s", err, reportOut)
	}
	res.TotalRequests = report.Requests
	for k, v := range report.StatusCodes {
		var code int
		if _, err := fmt.Sscanf(k, "%d", &code); err == nil {
			res.StatusCounts[code] = v
		}
	}

	// Optionally walk every response to capture Retry-After.
	if spec.CaptureResponseHeaders {
		encodeCmd := exec.Command(vegetaPath, "encode", "-to=json", resultsPath)
		encodeOut, err := encodeCmd.Output()
		if err != nil {
			t.Fatalf("load.Run: vegeta encode: %v\n%s", err, encodeOut)
		}
		// `vegeta encode -to=json` emits one JSON object per line.
		scanner := bufio.NewScanner(bytes.NewReader(encodeOut))
		// Bump scanner buffer: response bodies can exceed the
		// default 64KB line cap on FHIR error envelopes.
		scanner.Buffer(make([]byte, 256*1024), 4*1024*1024)
		for scanner.Scan() {
			line := scanner.Bytes()
			if len(bytes.TrimSpace(line)) == 0 {
				continue
			}
			var rec struct {
				Code    int                 `json:"code"`
				Headers map[string][]string `json:"headers"`
			}
			if err := json.Unmarshal(line, &rec); err != nil {
				t.Fatalf("load.Run: parse vegeta encode line: %v\nline=%s", err, string(line))
			}
			if rec.Code != http.StatusTooManyRequests {
				continue
			}
			for k, vs := range rec.Headers {
				if !strings.EqualFold(k, "Retry-After") {
					continue
				}
				for _, v := range vs {
					if v == "" {
						continue
					}
					res.RetryAfterValues = append(res.RetryAfterValues, v)
				}
			}
		}
		if err := scanner.Err(); err != nil {
			t.Fatalf("load.Run: scan vegeta encode output: %v", err)
		}
	}

	return res
}
