{{- if and .Values.externalSecrets.enabled (not .Values.externalSecrets.existingSecret) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fhir-subs.fullname" . }}
  labels:
    {{- include "fhir-subs.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef.name is required when externalSecrets.enabled" .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "fhir-subs.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range $key, $val := .Values.externalSecrets.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $val.remoteRef.key }}
        {{- if $val.remoteRef.property }}
        property: {{ $val.remoteRef.property }}
        {{- end }}
        {{- if $val.remoteRef.version }}
        version: {{ $val.remoteRef.version }}
        {{- end }}
    {{- end }}
{{- end }}
